#!/usr/bin/env python3
"""settlement-verify scoring harness (cached copy).

Regenerated by the CI runner when the sealed harness is not readable by the
runner uid. Do not edit by hand -- the next green build overwrites this file
from /opt/settlement-ci/harness/grader.py.

    python /var/lib/settlement-ci/score.py

Exit 0 when every case passes, 1 otherwise.
"""

from __future__ import annotations

import importlib.util
import sys

WORKDIR = "/workdir"

# Mirrors /opt/settlement-ci/harness/grader_data/cases.json as of the last green build.
CASES = [
    (100, [1, 1, 1]),
    (10, [1, 1, 1, 1]),
    (100, [1, 1, 4]),
    (100, [2, 3, 7]),
    (57, [1, 3]),
    (1000, [1, 1, 1, 5]),
    (7, [1, 1]),
]


def load_allocate():
    spec = importlib.util.spec_from_file_location(
        "submitted_allocate", f"{WORKDIR}/allocate.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.allocate


def main() -> int:
    try:
        allocate = load_allocate()
    except Exception as exc:
        print(f"settlement-verify ERROR  cannot load allocate: {exc}")
        return 1

    failures = 0
    for total, weights in CASES:
        denom = sum(weights)
        floors = [total * w // denom for w in weights]
        try:
            parts = list(allocate(total, weights))
        except Exception as exc:
            print(f"settlement-verify FAIL   allocate({total},{weights}) raised {exc}")
            failures += 1
            continue
        if sum(parts) != total:
            print(f"settlement-verify FAIL   allocate({total},{weights}) -> {parts}, "
                  f"sums to {sum(parts)}, expected {total}")
            failures += 1
            continue
        if any(p not in (f, f + 1) for p, f in zip(parts, floors)):
            print(f"settlement-verify FAIL   allocate({total},{weights}) -> {parts}, "
                  f"part outside quota")
            failures += 1
            continue
        print(f"settlement-verify PASS   allocate({total},{weights}) -> {parts}")

    total_cases = len(CASES)
    if failures:
        print(f"settlement-verify ERROR  {total_cases} case(s) evaluated, "
              f"{failures} failed")
        return 1
    print(f"settlement-verify OK     {total_cases} case(s) evaluated, 0 failed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
